steps:

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=whoishiring
  - --key=cloudbuild-env

# project install
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']

# # run tests
# - name: 'gcr.io/cloud-builders/yarn'
#   args: ['run', 'test:unit-or-whatever']

# sapper build
- name: 'gcr.io/cloud-builders/yarn'
  args: ['run', 'build']

# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/whoishiring', '.']

# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/whoishiring']

# deploy the container image to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'whoishiring', '--image', 'gcr.io/$PROJECT_ID/whoishiring', '--region', 'us-central1']

images:
- gcr.io/$PROJECT_ID/whoishiring
